services:
  - type: web
    name: n8n-upgraded
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: WEBHOOK_URL
        value: https://n8n-upgraded.onrender.com
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "lucus"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Lucus@2006"
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
      - key: N8N_PROTOCOL
        value: https
    disk:
      name: n8n-storage
      mountPath: /home/node/.n8n
      sizeGB: 1
